name: 'Chromatic'
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    # Turborepo remote caching
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      # Setup
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.5.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build svelte-og
        working-directory: packages/svelte-og
        run: pnpm build

      # Deploy to Chromatic
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: apps/web
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
